version: 2
jobs:
  build:
    working_directory: /tmp/build
    dependencies:
        cache_directories:
    - "~/.iv2/cache"
    - "~/.sbt"
    - "~/.m2"
    - "target/resolution-cache"
    - "target/streams"
    - "project/target/resolution-cache"
    - "project/target/streams"
    override:
        - sbt compile
    docker:
      - image: alpine
    steps:
      - checkout
      - setup_remote_docker
      - deploy:
          name: Publish to Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              apk --no-cache add docker bash
              docker login -u ${DOCKER_LOGIN} -p ${DOCKER_PASSWORD}
              bash ./build_multiple.sh
            fi